# Generated by Django 4.2.3 on 2026-05-07

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_agent_lead_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='revenue',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[MinValueValidator(Decimal('0'))],
            ),
        ),
    ]
