# Generated by Django 4.2.3 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(
                choices=[
                    ('🟢 New Lead', '🟢 New Lead'),
                    ('🔵 Contacted', '🔵 Contacted'),
                    ('🟡 Follow-Up', '🟡 Follow-Up'),
                    ('🟣 Negotiation', '🟣 Negotiation'),
                    ('🔴 Lost', '🔴 Lost'),
                    ('✅ Converted', '✅ Converted'),
                ],
                default='🟢 New Lead',
                max_length=30,
            ),
        ),
    ]
